apiVersion: v1
kind: Pod
metadata:
  name: pg3fy-test #Podname
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central
  containers:
  - name: xlogger #Podname
    image: nvcr.io/nvidia/pytorch:22.08-py3
    #image: gitlab-registry.nrp-nautilus.io/pg3fy/sleep-apnea-test:simple4
    #image: gitlab-registry.nrp-nautilus.io/pg3fy/test:test1
    #image: python
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    args: ["apt-get update", "apt-get -y install vim" , "pip install pytorch_lightning", "pip install tslearn", "pip install seaborn"] # THIS IS NEW
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1 ## ADDED NEW
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1 ## ADDED NEW
    
    volumeMounts:
      - mountPath: /pg3fy-centraldata #This is the folder name that appears when you access your pod
        name: pg3fy-central #pg3fy-pv#PVC
  volumes:
    - name: pg3fy-central #PVC
      persistentVolumeClaim:
        claimName: pg3fy-central #PVC
