apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg3fy-central
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
